name: neural-blend-shapes
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.12.0
  - aiohttp=3.6.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.4.13
  - cachetools=4.2.2
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.2
  - coverage=5.5
  - cpuonly=1.0=0
  - cryptography=3.4.7
  - cython=0.29.23
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.36.1
  - idna=2.10
  - importlib-metadata=3.10.0
  - intel-openmp=2021.2.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - libffi=3.3
  - libiconv=1.15
  - libidn2=2.3.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - multidict=4.7.6
  - ncurses=6.2
  - nettle=3.7.2
  - ninja=1.10.2
  - numpy=1.20.1
  - numpy-base=1.20.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.0.1
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.5
  - pytorch=1.8.1
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - chumpy==0.70
    - scipy==1.6.3
